Networkteam:
  Util:
    OpenExchangeRateConverter:
      appId: 'b05f50cd27864a519887e3141c64cb34'
      baseUrl: 'http://openexchangerates.org/api/'
      cacheDir: '%FLOW_PATH_DATA%Temporary/CurrencyCache'
      cacheTimeout: 84600
      baseCurrency: 'EUR'
#    Mailer:
#      bcc:
#        - some mail to bcc the sent mails to
#      overrideRecipients:
#        - some@anotherdomain will override all recipients set in a mailmessage to only this one

Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          networkteamUtilMailerLogger:
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                logFileURL: '%FLOW_PATH_DATA%Logs/Mailer.log'
                createParentDirectories: true
                severityThreshold: '%LOG_INFO%'
                maximumLogFileSize: 10485760
                logFilesToKeep: 1
